pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = 'PlateauLib'

include 'plateau-postprocess'
include 'plateau-particles'
include 'plateau-attributes'
include 'plateau-ui'
include 'plateau-sync-config'
include 'plateau-vfx'
include 'plateau-all'
